// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.epam.ievgen_kireiev.proto_rest.protos;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 id = 1;
    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string fname = 3;
    /**
     * <code>optional string fname = 3;</code>
     */
    boolean hasFname();
    /**
     * <code>optional string fname = 3;</code>
     */
    java.lang.String getFname();
    /**
     * <code>optional string fname = 3;</code>
     */
    com.google.protobuf.ByteString
        getFnameBytes();

    // optional string login = 4;
    /**
     * <code>optional string login = 4;</code>
     */
    boolean hasLogin();
    /**
     * <code>optional string login = 4;</code>
     */
    java.lang.String getLogin();
    /**
     * <code>optional string login = 4;</code>
     */
    com.google.protobuf.ByteString
        getLoginBytes();

    // optional string password = 5;
    /**
     * <code>optional string password = 5;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 5;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 5;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code com.epam.ievgen_kireiev.srvs.protos.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage
      implements UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private User(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }

    public User getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              fname_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              login_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              password_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.internal_static_com_epam_ievgen_kireiev_srvs_protos_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.internal_static_com_epam_ievgen_kireiev_srvs_protos_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.class, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.Builder.class);
    }

    public static com.google.protobuf.Parser<User> PARSER =
        new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string fname = 3;
    public static final int FNAME_FIELD_NUMBER = 3;
    private java.lang.Object fname_;
    /**
     * <code>optional string fname = 3;</code>
     */
    public boolean hasFname() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string fname = 3;</code>
     */
    public java.lang.String getFname() {
      java.lang.Object ref = fname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string fname = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFnameBytes() {
      java.lang.Object ref = fname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string login = 4;
    public static final int LOGIN_FIELD_NUMBER = 4;
    private java.lang.Object login_;
    /**
     * <code>optional string login = 4;</code>
     */
    public boolean hasLogin() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string login = 4;</code>
     */
    public java.lang.String getLogin() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          login_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string login = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLoginBytes() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        login_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string password = 5;
    public static final int PASSWORD_FIELD_NUMBER = 5;
    private java.lang.Object password_;
    /**
     * <code>optional string password = 5;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string password = 5;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      fname_ = "";
      login_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFnameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getLoginBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFnameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getLoginBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.epam.ievgen_kireiev.srvs.protos.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.internal_static_com_epam_ievgen_kireiev_srvs_protos_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.internal_static_com_epam_ievgen_kireiev_srvs_protos_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.class, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.Builder.class);
      }

      // Construct using com.epam.ievgen_kireiev.srvs.protos.UserProtos.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        fname_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        login_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.internal_static_com_epam_ievgen_kireiev_srvs_protos_User_descriptor;
      }

      public com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User getDefaultInstanceForType() {
        return com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.getDefaultInstance();
      }

      public com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User build() {
        com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User buildPartial() {
        com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User result = new com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fname_ = fname_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.login_ = login_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User) {
          return mergeFrom((com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User other) {
        if (other == com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasFname()) {
          bitField0_ |= 0x00000004;
          fname_ = other.fname_;
          onChanged();
        }
        if (other.hasLogin()) {
          bitField0_ |= 0x00000008;
          login_ = other.login_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000010;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 id = 1;
      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string fname = 3;
      private java.lang.Object fname_ = "";
      /**
       * <code>optional string fname = 3;</code>
       */
      public boolean hasFname() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string fname = 3;</code>
       */
      public java.lang.String getFname() {
        java.lang.Object ref = fname_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string fname = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFnameBytes() {
        java.lang.Object ref = fname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string fname = 3;</code>
       */
      public Builder setFname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string fname = 3;</code>
       */
      public Builder clearFname() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fname_ = getDefaultInstance().getFname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string fname = 3;</code>
       */
      public Builder setFnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fname_ = value;
        onChanged();
        return this;
      }

      // optional string login = 4;
      private java.lang.Object login_ = "";
      /**
       * <code>optional string login = 4;</code>
       */
      public boolean hasLogin() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string login = 4;</code>
       */
      public java.lang.String getLogin() {
        java.lang.Object ref = login_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          login_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string login = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLoginBytes() {
        java.lang.Object ref = login_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          login_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string login = 4;</code>
       */
      public Builder setLogin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        login_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string login = 4;</code>
       */
      public Builder clearLogin() {
        bitField0_ = (bitField0_ & ~0x00000008);
        login_ = getDefaultInstance().getLogin();
        onChanged();
        return this;
      }
      /**
       * <code>optional string login = 4;</code>
       */
      public Builder setLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        login_ = value;
        onChanged();
        return this;
      }

      // optional string password = 5;
      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 5;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string password = 5;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 5;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 5;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000010);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 5;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        password_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.epam.ievgen_kireiev.srvs.protos.User)
    }

    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.epam.ievgen_kireiev.srvs.protos.User)
  }

  public interface UsersOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;
    /**
     * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
     */
    java.util.List<com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User> 
        getUserList();
    /**
     * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
     */
    com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User getUser(int index);
    /**
     * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
     */
    int getUserCount();
    /**
     * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
     */
    java.util.List<? extends com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.UserOrBuilder> 
        getUserOrBuilderList();
    /**
     * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
     */
    com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.UserOrBuilder getUserOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.epam.ievgen_kireiev.srvs.protos.Users}
   */
  public static final class Users extends
      com.google.protobuf.GeneratedMessage
      implements UsersOrBuilder {
    // Use Users.newBuilder() to construct.
    private Users(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Users(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Users defaultInstance;
    public static Users getDefaultInstance() {
      return defaultInstance;
    }

    public Users getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Users(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                user_ = new java.util.ArrayList<com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User>();
                mutable_bitField0_ |= 0x00000001;
              }
              user_.add(input.readMessage(com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          user_ = java.util.Collections.unmodifiableList(user_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.internal_static_com_epam_ievgen_kireiev_srvs_protos_Users_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.internal_static_com_epam_ievgen_kireiev_srvs_protos_Users_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users.class, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users.Builder.class);
    }

    public static com.google.protobuf.Parser<Users> PARSER =
        new com.google.protobuf.AbstractParser<Users>() {
      public Users parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Users(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Users> getParserForType() {
      return PARSER;
    }

    // repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;
    public static final int USER_FIELD_NUMBER = 1;
    private java.util.List<com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User> user_;
    /**
     * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
     */
    public java.util.List<com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User> getUserList() {
      return user_;
    }
    /**
     * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
     */
    public java.util.List<? extends com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.UserOrBuilder> 
        getUserOrBuilderList() {
      return user_;
    }
    /**
     * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
     */
    public int getUserCount() {
      return user_.size();
    }
    /**
     * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
     */
    public com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User getUser(int index) {
      return user_.get(index);
    }
    /**
     * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
     */
    public com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.UserOrBuilder getUserOrBuilder(
        int index) {
      return user_.get(index);
    }

    private void initFields() {
      user_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < user_.size(); i++) {
        output.writeMessage(1, user_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < user_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, user_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.epam.ievgen_kireiev.srvs.protos.Users}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.UsersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.internal_static_com_epam_ievgen_kireiev_srvs_protos_Users_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.internal_static_com_epam_ievgen_kireiev_srvs_protos_Users_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users.class, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users.Builder.class);
      }

      // Construct using com.epam.ievgen_kireiev.srvs.protos.UserProtos.Users.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          userBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.internal_static_com_epam_ievgen_kireiev_srvs_protos_Users_descriptor;
      }

      public com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users getDefaultInstanceForType() {
        return com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users.getDefaultInstance();
      }

      public com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users build() {
        com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users buildPartial() {
        com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users result = new com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users(this);
        int from_bitField0_ = bitField0_;
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            user_ = java.util.Collections.unmodifiableList(user_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users) {
          return mergeFrom((com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users other) {
        if (other == com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users.getDefaultInstance()) return this;
        if (userBuilder_ == null) {
          if (!other.user_.isEmpty()) {
            if (user_.isEmpty()) {
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUserIsMutable();
              user_.addAll(other.user_);
            }
            onChanged();
          }
        } else {
          if (!other.user_.isEmpty()) {
            if (userBuilder_.isEmpty()) {
              userBuilder_.dispose();
              userBuilder_ = null;
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000001);
              userBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUserFieldBuilder() : null;
            } else {
              userBuilder_.addAllMessages(other.user_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.Users) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;
      private java.util.List<com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User> user_ =
        java.util.Collections.emptyList();
      private void ensureUserIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          user_ = new java.util.ArrayList<com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User>(user_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.Builder, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.UserOrBuilder> userBuilder_;

      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public java.util.List<com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User> getUserList() {
        if (userBuilder_ == null) {
          return java.util.Collections.unmodifiableList(user_);
        } else {
          return userBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public int getUserCount() {
        if (userBuilder_ == null) {
          return user_.size();
        } else {
          return userBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User getUser(int index) {
        if (userBuilder_ == null) {
          return user_.get(index);
        } else {
          return userBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public Builder setUser(
          int index, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.set(index, value);
          onChanged();
        } else {
          userBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public Builder setUser(
          int index, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.set(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public Builder addUser(com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(value);
          onChanged();
        } else {
          userBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public Builder addUser(
          int index, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(index, value);
          onChanged();
        } else {
          userBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public Builder addUser(
          com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public Builder addUser(
          int index, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public Builder addAllUser(
          java.lang.Iterable<? extends com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User> values) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          super.addAll(values, user_);
          onChanged();
        } else {
          userBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          userBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public Builder removeUser(int index) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.remove(index);
          onChanged();
        } else {
          userBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.Builder getUserBuilder(
          int index) {
        return getUserFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.UserOrBuilder getUserOrBuilder(
          int index) {
        if (userBuilder_ == null) {
          return user_.get(index);  } else {
          return userBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public java.util.List<? extends com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.UserOrBuilder> 
           getUserOrBuilderList() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(user_);
        }
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.Builder addUserBuilder() {
        return getUserFieldBuilder().addBuilder(
            com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.getDefaultInstance());
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.Builder addUserBuilder(
          int index) {
        return getUserFieldBuilder().addBuilder(
            index, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.getDefaultInstance());
      }
      /**
       * <code>repeated .com.epam.ievgen_kireiev.srvs.protos.User user = 1;</code>
       */
      public java.util.List<com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.Builder> 
           getUserBuilderList() {
        return getUserFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.Builder, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.User.Builder, com.epam.ievgen_kireiev.proto_rest.protos.UserProtos.UserOrBuilder>(
                  user_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.epam.ievgen_kireiev.srvs.protos.Users)
    }

    static {
      defaultInstance = new Users(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.epam.ievgen_kireiev.srvs.protos.Users)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_epam_ievgen_kireiev_srvs_protos_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_epam_ievgen_kireiev_srvs_protos_User_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_epam_ievgen_kireiev_srvs_protos_Users_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_epam_ievgen_kireiev_srvs_protos_Users_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022#com.epam.ievgen_kireiev.sr" +
      "vs.protos\"P\n\004User\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 " +
      "\001(\t\022\r\n\005fname\030\003 \001(\t\022\r\n\005login\030\004 \001(\t\022\020\n\010pas" +
      "sword\030\005 \001(\t\"@\n\005Users\0227\n\004user\030\001 \003(\0132).com" +
      ".epam.ievgen_kireiev.srvs.protos.UserB1\n" +
      "#com.epam.ievgen_kireiev.srvs.protosB\nUs" +
      "erProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_epam_ievgen_kireiev_srvs_protos_User_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_epam_ievgen_kireiev_srvs_protos_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_epam_ievgen_kireiev_srvs_protos_User_descriptor,
              new java.lang.String[] { "Id", "Name", "Fname", "Login", "Password", });
          internal_static_com_epam_ievgen_kireiev_srvs_protos_Users_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_epam_ievgen_kireiev_srvs_protos_Users_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_epam_ievgen_kireiev_srvs_protos_Users_descriptor,
              new java.lang.String[] { "User", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
